### ISSUE TITLE
The example does not work

### ISSUE THREAD

**Issue by marjanSterjev** [kksharma1618/lamda-restify#2]
Hi,
As suggested, I'm using Node.js version is 6.10.2.

The following code
```
'use strict';

const Server = require('lambda-restify');
const server = new Server();
```

throws an error:

TypeError: Server is not a constructor

What should we do make this work?

**Comment by kksharma1618** [comment]
Hey,

Thanks for reporting the issue.
Documentation seems to be wrong. I will update it in the next push.

It should be:
```
const Server = require('lambda-restify').default;
const server = new Server(options);
```
instead of
```
const Server = require('lambda-restify');
const server = new Server(options);
```
If you are using es6 import:
```
import Server from 'lambda-restify';
const server = new Server(options);
```

**Comment by marjanSterjev** [comment]
Thanks for your quick reply, but it seems that is not the only issue. I'm trying to use Microsoft BotBuilder with your wrapper, but it seems they are not compatible yet (more TypeErros).

**Comment by kksharma1618** [comment]
I am not familiar with microsoft bot builder. Can you provide the error stack?
