### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by JesterXL** [kksharma1618/lamda-restify#4]
Not an issue, I couldn't find your contact info, so just saying thank you for this awesome project! Once I figured out how to get API Gateway Proxy resource setup, she works great man. 

![who-is-awesome](https://user-images.githubusercontent.com/424737/34469402-1e8c6a30-eeec-11e7-9d22-fca67b437b6f.jpg)

**Comment by kksharma1618** [comment]
Thanks for the feedback, Jexter. You are awesome.
